AWSTemplateFormatVersion: 2010-09-09
Description: "CodeBuild IAM Role"
Parameters:
  PjName:
    Type: String
    Default: cicdhandson

Resources:
  CiCdHandsonCodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CiCdHandsonCodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "codebuild.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - !Ref CiCdHandsonCodeBuildPolicy
      Tags:
        - Key: Name
          Value: !Sub "${PjName}"
  CiCdHandsonCodeBuildPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      ManagedPolicyName: codebuild-role
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:DescribeStacks"
              - "cloudformation:CreateChangeSet"
              - "cloudformation:ExecuteChangeSet"
              - "cloudformation:DeleteChangeSet"
              - "cloudformation:DescribeStackEvents"
              - "cloudformation:GetTemplateSummary"
              - "cloudformation:ValidateTemplate"
              - "cloudformation:ListStacks"
              - "iam:CreateRole"
              - "iam:DeleteRole"
              - "iam:AttachRolePolicy"
              - "iam:GetRole"
              - "iam:PassRole"
              - "codedeploy:CreateDeployment"
              - "codedeploy:DeleteDeployment"
              - "codedeploy:CreateApplication"
              - "codedeploy:DeleteApplication"
              - "codedeploy:CreateDeploymentGroup"
              - "codedeploy:DeleteDeploymentGroup"
              - "codedeploy:GetDeploymentConfig"
              - "codedeploy:GetDeployment"
              - "codedeploy:RegisterApplicationRevision"
              - "codedeploy:GetDeploymentGroup"
              - "lambda:CreateFunction"
              - "lambda:DeleteFunction"
              - "lambda:TagResource"
              - "lambda:GetFunction"
              - "lambda:ListVersionsByFunction"
              - "lambda:ListTags"
              - "lambda:PublishVersion"
              - "lambda:CreateAlias"
              - "lambda:DeleteAlias"
              - "lambda:GetAlias"
              - "lambda:UpdateFunctionCode"
              - "lambda:UpdateFunctionConfiguration"
              - "iam:PutRolePolicy"
              - "iam:DetachRolePolicy"
              - "iam:DeleteRolePolicy"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
              - "logs:CreateLogGroup"
            Resource: "*"
          - Effect: Allow
            Action:
              - "s3:PutObject"
              - "s3:GetObject"
              - "s3:GetObjectVersion"
              - "s3:GetBucketAcl"
              - "s3:GetBucketLocation"
            Resource:
              - !Join
                - ""
                - - !ImportValue CICDHandsonBucketArn
                  - "/*"
              - !ImportValue CICDHandsonBucketArn
              - !Join
                - ""
                - - !ImportValue CICDSamBucketArn
                  - "/*"
              - !ImportValue CICDSamBucketArn
Outputs:
  CiCdHandsonCodeBuildRoleName:
    Value: !Ref CiCdHandsonCodeBuildRole
    Export:
      Name: CodeBuildRoleName
